services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB-NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - COGNITO_REGION=${COGNITO_REGION}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - REDIS_URL=${REDIS_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - pgnetwork
      - codeclash-net

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - pgnetwork

  # test-db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: ${DB_TEST_USER}
  #     POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
  #     POSTGRES_DB: ${DB_TEST_NAME}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_test_data:/var/lib/postgresql/data
  #     - ./database:/docker-entrypoint-initdb.d
  #   networks:
  #     - pgnetwork

  redis:
    image: redis:8.6.3-alpine
    container_name: codeclash-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - ./backend/src/frameworks-drivers/config/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: unless-stopped
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - "${PGADMIN_PORT}:5151"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pgnetwork

volumes:
  postgres_data:
  postgres_test_data:
  pgadmin_data:
  redis-data:
    driver: local

networks:
  pgnetwork:
  codeclash-net:
    external: true
