services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/codeclash
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #TODO IMPORTANT return this when we want to containerise the front end for deployment

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # judge0:
  #   image: judge0/judge0:latest
  #   ports:
  #     - "2358:2358"
  #   privileged: true
  #TODO IMPORTANT return this when we want to start implementing code execution


  redis:
    image: redis:8.6.3-alpine
    container_name: codeclash-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: --requirepass ${REDIS_PASS} --appendonly yes
    restart: unless-stopped

  redis:
    image: redis:8.6.3-alpine
    container_name: codeclash-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: --requirepass ${REDIS_PASS} --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  redis-data:
    driver: local