services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/codeclash
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks: 
      - pgnetwork

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #TODO IMPORTANT return this when we want to containerise the front end for deployment

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:9.15
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - "${PGADMIN_PORT}:5151"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pgnetwork
  # judge0:
  #   image: judge0/judge0:latest
  #   ports:
  #     - "2358:2358"
  #   privileged: true
  #TODO IMPORTANT return this when we want to start implementing code execution

volumes:
  postgres_data:
  pgadmin_data: 

networks:
  pgnetwork: