import "../../../../src/styles/global.css"
import React from "react"
import { Button } from "@/components/ui/button";
import { ChevronDown, ChevronUp } from "lucide-react";

interface PowerUpAndDownButtonsProps {
    children?: React.ReactNode;
    className?: string;
}


export const PowerUpAndDownButtons = ({children, className} : PowerUpAndDownButtonsProps) => {
    //the code below was copied from another file that was overwritten when merged (it was saved before merging),
    //all this pasted code was hand-written and not generated by ai
    return(
        <div className={`flex flex-row gap-5 bg-background-elevated border border-border rounded-3xl py-2 px-2 h-[70%] ${className}`}>
                <Button className="card-elevated h-11 w-30 rounded-full my-auto">
                    <div className="flex flex-row">
                        <ChevronUp className="text-[var(--match-box)] size-6.5"/>
                        <h1 className="text-[1rem] text-[var(--match-box)] font-semibold my-auto mx-auto">Powerups</h1>
                    </div>
                </Button>

                <Button className="card-elevated h-11 w-31 rounded-full my-auto">
                    <div className="flex flex-row">
                        <ChevronDown className="text-[var(--match-box)] size-6.5"/>
                        <h1 className="text-[0.9rem] text-[var(--match-box)] font-semibold my-auto">Powerdowns</h1>
                    </div>
                </Button>

                {children}

        </div>
    );

}