import "../../../../src/styles/global.css"
// import React from "react"
// import { Button } from "@/components/ui/button";
// import { ChevronDown, ChevronUp } from "lucide-react";
// import { useState } from "react";
// import PowerupPopup from "src/Views/Match/PowerupsPopup";
// import { useMatch } from "src/ViewModels/Match/MatchViewModel";

// interface PowerUpAndDownButtonsProps {
//     children?: React.ReactNode;
//     className?: string;
// }


// export const PowerUpAndDownButtons = ({children, className} : PowerUpAndDownButtonsProps) => {
//     //the code below was copied from another file that was overwritten when merged (it was saved before merging),
//     //all this pasted code was hand-written and not generated by ai

//     const [popupFilter, setPopupFilter] = useState<'powerup' | 'powerdown' | null>(null);
//     // const { usePowerups } = useMatch();

//     const openPowerups = () => setPopupFilter('powerup');
//     const openPowerdowns = () => setPopupFilter('powerdown');
//     const closePopup = () => setPopupFilter(null);

//     // const handleConfirm = async (itemIds: string[]) => {
//     //     await usePowerups(itemIds);
//     //     closePopup();
//     // };

//     return(
//         <div className={`flex flex-row gap-5 bg-background-elevated border border-border rounded-3xl py-2 px-2 h-[70%] ${className}`}>
//                 <Button className="card-elevated h-11 w-30 rounded-full my-auto" onClick={openPowerups}>
//                     <div className="flex flex-row">
//                         <ChevronUp className="text-[var(--match-box)] size-6.5"/>
//                         <h1 className="text-[1rem] text-[var(--match-box)] font-semibold my-auto mx-auto">Powerups</h1>
//                     </div>
//                 </Button>

//                 <Button className="card-elevated h-11 w-31 rounded-full my-auto" onClick={openPowerdowns}>
//                     <div className="flex flex-row">
//                         <ChevronDown className="text-[var(--match-box)] size-6.5"/>
//                         <h1 className="text-[0.9rem] text-[var(--match-box)] font-semibold my-auto">Powerdowns</h1>
//                     </div>
//                 </Button>

//                 {children}

//                 {/* <PowerupPopup
//                     isOpen={popupFilter !== null}
//                     onClose={closePopup}
//                     // onConfirm={handleConfirm}
//                 /> */}

//         </div>
//     );

// }