import { cn } from "@/lib/utils"
import { Target, Check, X, LockKeyhole } from "lucide-react"
import type { QuestionDTO } from "src/dtos/match/match.dto"
import { Progress } from "@/components/ui/progress"

interface RoundTreeProps {
    rounds: QuestionDTO[][],
    results: (boolean | null)[][],
    current_round: number,
    current_question: number,
    opponent_progress?: {round: number, question: number},
    className?: string
}

export const RoundTree = ({
    rounds,
    results,
    current_round,
    current_question,
    opponent_progress,
    className

}: RoundTreeProps) => {
    return (
        <div className={cn("flex flex-col gap-4 h-full", className)}>
            {rounds.map((round_question, round_idx) => {
                const round_key = round_question.map(q => q.id).join('-');
                const past_round = round_idx < current_round;
                const current = round_idx === current_round;
                const next_round = round_idx > current_round;


                const questionsAnswered = (results[round_idx] ?? []).filter((qr) => qr === true || qr === false).length;
                const progressValue = rounds[current_round].length > 0 ? (questionsAnswered / rounds[current_round].length) * 100 : 0

                return (
                    <div key={round_key} className="flex flex-col gap-1" >
                        <span
                            className={cn("text-sm font-bold mb-1", current && "text-button-tournament", next_round && "text-muted-text/50", past_round && "text-button-tournament-secondary")}
                        >
                            Round {round_idx + 1}
                        </span>

                        <div className="relative flex flex-col-reverse items-center mx-auto ml-6">
                            <Progress
                                value={progressValue}
                                orientation="vertical"
                                className="absolute top-0 bottom-3 w-2 rounded-3xl bg-card opacity-40"
                            />
                            {round_question.map((question, q_idx) => {
                                const result = results[round_idx]?.[q_idx];
                                const is_current = current && q_idx === current_question;
                                const next = next_round || (current && q_idx > current_question);
                                
                                //the following block of code was pasted from another version of match.tsx and edited in this file,
                                //this code is not generated by ai and was simply written by hand and pasted here for the sake of time
                                const doorSymbol = () => {
                                    if (is_current) return <Target size={35} className="font-black text-button-tournament drop-shadow-[0_0_8px_rgba(255,81,106,0.6)]"/>
                                    if (result === true) return <Check size={35} className="text-success drop-shadow-[0_0_8px_rgba(134,239,172,0.9)] font-semibold"/>
                                    if (result === false) return <X size={35} className="text-danger font-semibold drop-shadow-[0_0_8px_rgba(198,40,40,0.9)]"/>
                                    return <LockKeyhole/>
                                }
                                const oppProg = () => {
                                    if (q_idx === opponent_progress?.question && round_idx === opponent_progress?.round) return <div className="absolute top-0 left-0 rounded-full h-3 w-3 
                                    bg-red-800 z-20 shadow-[0_0_12px_rgba(190,0,0,0.3)]"/>
                                }
                                /////////////////////////////////////////////

                                return(
                                    <div key={question.id} className={`
                                        
                                        flex items-center text-center justify-center py-1 text-xs", 
                                    is_current && "text-button-tournament font-semibold",
                                    next && "text-muted-text/50`
                                    }>

                                        {/* <span className="-ml-[9px]">-</span> */}
                                        {doorSymbol()}
                                        {oppProg()}

                                    </div>
                                )
                            })}
                        </div>
                    </div>
                )
            })}

        </div>
    )
}