import {motion} from 'framer-motion';
import thinking from "../../svgs/thinking.svg"
import leftShoulder from "../../svgs/left-shoulder.svg"
import leftArm from "../../svgs/left-forearm.svg"
import leftHand from "../../svgs/left-hand.svg"
import leftLeg from "../../svgs/left-leg.svg"
import rightShoulder from "../../svgs/right-shoulder.svg"
import rightArm from "../../svgs/right-forearm.svg"
import rightHand from "../../svgs/right-hand.svg"
import rightLeg from "../../svgs/right-leg.svg"
import torso from "../../svgs/torso.svg"

export const Thinking = () => {
    return(
        <svg viewBox="0 0 300 400" width="600" height="700" preserveAspectRatio="xMidYMid meet">
            <motion.g>

                <image href={torso} width="50" x="60" y="40" height="120"/>
                <image href={thinking} width="50" x="60" y="40" height="45"/>
            

            {/* the below segment of code is copied and pasted from my hand-written code on another page to save time, this code was not generated by ai */}
                <motion.g>
                    <image href={leftShoulder} width="50" x="93" y="92" height="55"/>
                        <motion.g>
                            <image href={leftArm} width="50" x="95" y="117" height="25"/>
            
                                <motion.g>
                                    <image href={leftHand} width="50" x="94" y="131" height="17"/>
                                </motion.g>
                        </motion.g>
                </motion.g>
            
                </motion.g>


        </svg>
    )
}