import Atlas from './Atlas.png';
import Axiom from './Axiom.png';
import Brix from './Brix.png';
import Kairo from './Kairo.png';
import Nyx from './Nyx.png';
import Riven from './Riven.png';
import Vexa from './Vexa.png';
import Xara from './Xara.png';
import Zen from './Zen.png';