import { useState, useEffect, useCallback } from 'react'
// import type { LeaderboardUserProps } from 'src/Models/LeaderboardModel';
import { type PaginatedLeaderboardResponse, type LeaderboardUserProps } from 'src/Models/LeaderboardModel';
import { useAuth } from 'src/context/Auth/hooks/useAuth';
import { getEquippedFor } from 'src/services/shop.service';

export async function fetchLeaderboard(limit: number, page: number, token: string): Promise<PaginatedLeaderboardResponse> {
  const response = await fetch(`/api/leaderboard?limit=${limit}&page=${page}`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  }
  );
  if (!response.ok) throw new Error('Failed to fetch leaderboard')
  const json = await response.json();
  return json;
}

export function LeaderboardViewModel(league: string) {
  const { token } = useAuth()
  const [userData, setUserData] = useState<LeaderboardUserProps[]>([]);
  const [topThree, setTopThree] = useState<LeaderboardUserProps[]>([]);
  const [isLoadingData, setIsLoadingData] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [firstAvatar, setFirstAvatar] = useState<string | null>(null);
  const [secondAvatar, setSecondAvatar] = useState<string | null>(null);
  const [thirdAvatar, setThirdAvatar] = useState<string | null>(null);
  const pageSize = 10;

  const tokenInv = token ?? "";

  const loadLeaderboard = useCallback(async (p: number) => { //useCallback is used so that returned data is cached until any values of the returned data is changed
    setIsLoadingData(true);
    setError(null);
    try {
      const response = await fetchLeaderboard(pageSize, p, token!);
      // setUserData(response.data);
      // setTotalPages(Math.ceil(response.total / pageSize));
      const mapped: LeaderboardUserProps[] = response.data.map(entry => ({
        user_id: entry.user_id,
        username: entry.username,
        elo: entry.rating !== undefined ? entry.rating : 0,
        avatar: ""
      }));
      setUserData(mapped);
      setTotalPages(Math.max(1, Math.ceil(response.total / pageSize)));

      const topThreeMapped = mapped.slice(0,3);

      if (p === 1) {
        setTopThree(topThreeMapped);
      }

      const topThreeAvatars = await Promise.all(
        topThreeMapped.map(async (u: any) => {
          //the below code was copied from friendsWithAvatars above - this code was not generated by ai and was written by hand!
          // it was simply pasted for the sake of time
          const { avatarImage } = await getEquippedFor(u.user_id, tokenInv);
          const avatarCrop = avatarImage?.replace("/src/assets/Shop/Avatars/", "");
          const avatarEndCrop = avatarCrop?.replace(".png", "");
          const avatarImg = avatarEndCrop ?? "";
          return { avatar: avatarImg }
        })
      )

      console.log("top three", topThree)
      console.log("top three avatars", topThreeAvatars)

      setFirstAvatar(topThreeAvatars[0]?.avatar ?? "");
      setSecondAvatar(topThreeAvatars[1]?.avatar ?? "");
      setThirdAvatar(topThreeAvatars[2]?.avatar ?? "");

    }
    catch (err) {
      setError(`Could not load User Data ${err}`);
    }
    finally {
      setIsLoadingData(false);
    }
  }, [league]);

  useEffect(() => {
    loadLeaderboard(page);
  }, [page, loadLeaderboard]);

  const nextPage = () => {
    if (page < totalPages) {
      setPage(p => p + 1);
    }
  }

  const prevPage = () => {
    if (page > 1) {
      setPage(p => p - 1);
    }
  }

  return {
    userData, topThree, firstAvatar, secondAvatar, thirdAvatar, isLoadingData, error, page, totalPages, setPage, nextPage, prevPage,
    refresh: () => loadLeaderboard(page)
  }


}
