import { MathfieldElement } from 'mathlive';
import { useEffect, useState, useRef, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { useSocket } from "src/context/Socket/hooks/useSocket";
// import { robot_map } from 'src/assets/Robots';
import { useLoadRounds, useMatchProgress, useMatchTimer, useOpponentProgress } from 'src/services/match.service';

import { useMatchStore } from 'src/stores/match-store';
import { useMatchmaking } from 'src/context/Matchmaking/hooks/useMatchmaking';
import { useAnswerResponse, useLifeShake, useSubmission } from 'src/services/submission.service';
import type { Player } from 'src/Models/MatchModel';
import { useResultStore } from 'src/stores/result-store';
import { getCurrentPlayerIndex } from 'src/services/match.service';
import { useAuth } from 'src/context/Auth/hooks/useAuth';
import { getEquippedFor } from 'src/services/shop.service';
import { useUser } from 'src/context/User/hooks/useUser';


export const useMatch = (timeUp?: () => Promise<void>) => {
    const nav = useNavigate();
    const { matchSocket } = useSocket();
    const status = useMatchStore(state => state.status);
    const matchmaking = useMatchmaking();

    // the stored copies survive a reload, the matchmaking context doesn't
    const matchMode = useMatchStore(state => state.match_mode) ?? matchmaking.matchMode;
    const matchType = useMatchStore(state => state.match_type) ?? matchmaking.matchType;
    const end_time = useMatchStore(state => state.end_time);
    const tournament_id = useMatchStore(state => state.tournament_id);
    const {token} = useAuth();
    const {username} = useUser();

    const tokenInv = token ?? ""

    const [currentQuestion, setCurrentQuestion] = useState(() => useMatchStore.getState().current_question);
    const [gameOver, setGameOver] = useState(false);
    const [nextRound, setNextRound] = useState(false);
    const [loading, setLoading] = useState(false);
    const [waitingOpponent, setWaitingOpponent] = useState(false);
    const [roundIdx, setRoundIdx] = useState(() => useMatchStore.getState().round_idx);
    const [confirmRound, setConfirmRound] = useState(false);
    // const [powerupPopupOpen, setPowerupPopupOpen] = useState(false);
    const [playerOneAvatar, setPlayerOneAvatar] = useState<string | null>(null);
    const [playerTwoAvatar, setPlayerTwoAvatar] = useState<string | null>(null);


    const finished_ref = useRef(false);
    const mathfieldRef = useRef<MathfieldElement | null>(null)


    const players = useMatchStore(state => state.players) as Player[];

    
    const stored_rounds = useMatchStore(state => state.rounds)!;
    const match_id = useMatchStore(state => state.match_id);
    const ids = useMemo(() => players.map(p => p.id), [players])


    useEffect(() => {
        if(!ids[0] || !tokenInv){
            return
        }

        let cancelled = false;

        getEquippedFor(ids[0], tokenInv).then(({ avatarImage }) => {
            const avatarImg = avatarImage ?? "";
            // const avatarCropStart = avatarImg.replace("/src/assets/Shop/Avatars/", "");
            // const avatarCropEnd = avatarCropStart.replace(".png", "");
            // const avatarImageCrop = avatarCropEnd ?? "";

            if(!cancelled){
                setPlayerOneAvatar(avatarImg)
            }
        }).catch((err) => {
            console.error('Failed to fetch player 1 avatar', err);
        });

        return () => { cancelled = true; };
    }, [ids[0], tokenInv])


    // the below code was hand written and not generated by ai, i simply pasted it from above to save some time

    useEffect(() => {
        if(!ids[1] || !tokenInv){
            return
        }

        let cancelled = false;

        getEquippedFor(ids[1], tokenInv).then(({ avatarImage }) => {
            const avatarImg = avatarImage ?? "";
            // const avatarCropStart = avatarImg.replace("/src/assets/Shop/Avatars/", "");
            // const avatarCropEnd = avatarCropStart.replace(".png", "");
            // const avatarImageCrop = avatarCropEnd ?? "";

            if(!cancelled){
                setPlayerTwoAvatar(avatarImg)
            }
        }).catch((err) => {
            console.error('Failed to fetch player 2 avatar', err);
        });

        return () => { cancelled = true; };
    }, [ids[1], tokenInv])



    const { rounds, duration } = useLoadRounds(stored_rounds, match_id);
    const questions = rounds[roundIdx] ?? [];
    const { playerLife, updatePlayerLife } = useMatchProgress(players);
    const { opponentProgress, handleOpponentDone, opponentCurrent, opponentDone } = useOpponentProgress(rounds, players, updatePlayerLife);


    const { submissionError, submitQuestion, results, setResults, lastResult, marking, markingError } = useSubmission({ round_idx: roundIdx, curr_question: currentQuestion, question: questions[currentQuestion], match_id: match_id!, updatePlayerLife })
    const { seconds, minutes } = useMatchTimer(duration, end_time, async () => {
        setGameOver(true);
        if (timeUp) {
            await timeUp();
        }
        else {

            await finishMatch(!tournament_id);
        }
    })

    useEffect(() => {
        useMatchStore.getState().setProgress(roundIdx, currentQuestion);
    }, [roundIdx, currentQuestion])

    const last_round = rounds.slice(roundIdx + 1).every(round => round.length === 0);
    const last_q_of_round = questions.length > 0 && currentQuestion === questions.length - 1;
    const complete_round = last_q_of_round && !last_round;
    const final_question = last_q_of_round && last_round;

    // const avatars = useMemo(() => players.map(p => robot_map[p.avatar_id]), [players]);
    const usernames = useMemo(() => players.map(p => p.username), [players]);
    const elos = useMemo(() => players.map(p => p.elo), [players]);
    const colourClass = useAnswerResponse(lastResult, currentQuestion);
    const shake = useLifeShake(lastResult);


    //the below line of code was copied from another branch's version of this file and was not generated by ai!
    const myIndex = useMemo(() => getCurrentPlayerIndex(players, username), [players, username])

    const closeLoading = () => setLoading(false);

    const nextQuestion = (curr: number) => {
        if (curr < questions.length - 1) {
            setCurrentQuestion(curr + 1);
        }
    }

    const prevQuestion = (curr: number) => {
        if (curr > 0) {
            setCurrentQuestion(curr - 1)
        }
    }

    const confirmCompleteRound = () => {
        if (complete_round || final_question) setConfirmRound(true);
    }

    const cancelCompleteRound = () => {
        setConfirmRound(false);
    }

    const completeRound = () => {
        if (!complete_round) return;
        setConfirmRound(false);
        setRoundIdx(r => r + 1);
        setCurrentQuestion(0);
        setNextRound(true);
        setTimeout(() => setNextRound(false), 500);
    }

    const finishMatch = async (force = false) => {
        // if (!final_question) return;
        if (!matchSocket || finished_ref.current || (!final_question && !force)) return;
        setWaitingOpponent(true);
        finished_ref.current = true;

        const response = await matchSocket?.finishMatch({ match_id: match_id!, match_type: matchType! });

        if (response?.ok)
            useResultStore.getState().addResult(response.data!);
    }

    const both_done = async () => {
        // useMatchStore.getState().reset();
        setWaitingOpponent(false);
        nav(`/results/${match_id}`, {
            replace: true,
            state: { id: match_id }
        });
    }

    // puts back what the server knows based on the match stored state (clock, lives, answers, opponent's question) after a reload or reconnect
    const rejoin = async (socket: NonNullable<typeof matchSocket>, id: string) => {
        try {
            const response = await socket.rejoinMatch({ match_id: id });
            if (!response.ok || !response.data) throw new Error("Match not found");
            const state = response.data;

            if (state.completed) {
                await both_done();
                return;
            }

            useMatchStore.getState().setEndTime(state.end_time, state.server_time);
            state.players.forEach(player => updatePlayerLife(player.id, player.life));
            if (state.opponent_progress) opponentProgress(state.opponent_progress);
            if (state.opponent_done) handleOpponentDone();

            const restored: (boolean | null)[][] = rounds.map(() => []);
            for (const submission of state.submissions) {
                const index = rounds[submission.round_number]?.findIndex(q => q.id === submission.question_id) ?? -1;
                if (index !== -1) restored[submission.round_number]![index] = submission.correct;
            }   
            setResults(restored);

            if (state.done) {
                finished_ref.current = true;
                setWaitingOpponent(true);
            }
        }
        catch {
            // the server no longer has this match, so there's nothing to go back to
            useMatchStore.getState().reset();
            nav('/dashboard', { replace: true });
        }
    }

    // const openPowerupPopup = () => setPowerupPopupOpen(true);
    // const closePowerupPopup = () => setPowerupPopupOpen(false);

    // const usePowerups = async (itemIds : string[]) => {
    //     if(!matchSocket || !match_id){
    //         return;
    //     }

    //     for(const shop_item_id of itemIds){
    //         try{
    //             const response = await matchSocket.usePowerup({
    //                 match_id: Number(match_id),
    //                 shop_item_id,
    //             });
    //             if (response.ok){
    //                 //put ui effects here 
                    
    //             }
    //         } catch (err) {
    //             console.error('Failed to use powerup', err);
    //         }
    //     }

    //     setPowerupPopupOpen(false);
    // }

    // const openPowerupPopup = () => setPowerupPopupOpen(true);
    // const closePowerupPopup = () => setPowerupPopupOpen(false);

    // const usePowerups = async (itemIds : string[]) => {
    //     if(!matchSocket || !match_id){
    //         return;
    //     }

    //     for(const shop_item_id of itemIds){
    //         try{
    //             const response = await matchSocket.usePowerup({
    //                 match_id: Number(match_id),
    //                 shop_item_id,
    //             });
    //             if (response.ok){
    //                 //put ui effects here 
                    
    //             }
    //         } catch (err) {
    //             console.error('Failed to use powerup', err);
    //         }
    //     }

    //     setPowerupPopupOpen(false);
    // }

    useEffect(() => {
        if (matchSocket && match_id) {
            setLoading(true);


            const unsub_submission_error = matchSocket.submissionError(submissionError);
            const unsub_done = matchSocket.bothDone(both_done);
            const unsub_opponent_progress = matchSocket.opponentProgress(opponentProgress);
            const unsub_opponent_done = matchSocket.opponentDone(handleOpponentDone);


            // const unsub_powerup_received = matchSocket.powerupReceived((data) => {
            //     //tangible effects like actually gaining health points or your elo going up idk
            // });

            // const unsub_powerup_blocked = matchSocket.powerupBlocked((data) => {
            //     //show blocked by shield feedback
            // });

            const unsub_clear_input = matchSocket.clearInput(() => {
                if(mathfieldRef.current) mathfieldRef.current.value = '';
            })

            const unsub_corrupt_input = matchSocket.corruptInput(() => {

            })

            

            setLoading(questions.length === 0);
          void rejoin(matchSocket, match_id); // no longer skips for tournaments and will just rejoin no matter what kind of game it is
            // if (!tournament_id) void rejoin(matchSocket, match_id);

            return () => {
                unsub_submission_error();
                unsub_done();
                unsub_opponent_progress();
                unsub_opponent_done();
                // unsub_powerup_received();
                // unsub_powerup_blocked();
                unsub_clear_input();
                unsub_corrupt_input();
            }
        }

    }, [matchSocket, match_id])

    return {
        lastResult,
        myIndex,
        status,
        players,
        questions,
        playerLife,
        playerOneAvatar,
        playerTwoAvatar,
        seconds,
        minutes,
        usernames,
        currentQuestion,
        nextQuestion,
        prevQuestion,
        loading,
        closeLoading,
        mathfieldRef,
        results,
        gameOver,
        waitingOpponent,
        finishMatch,
        opponentCurrent,
        opponentDone,
        submitQuestion,
        marking,
        markingError,
        nextRound,
        roundIdx,
        total_rounds: rounds.length,
        rounds,
        elos,
        colourClass,
        shake,
        complete_round,
        final_question,
        confirmRound,
        confirmCompleteRound,
        cancelCompleteRound,
        completeRound,
        matchType,
        matchMode
    }
}