import React from 'react' 
import { Card } from "../ui/card"
import { Calculator, Timer, ArrowRight, CodeXml } from "lucide-react"
import "../../../src/styles/global.css"
import { Progress } from "./progress"
import TournamentButton from "./TournamentButton"
import { MatchCard } from './MatchCard'

interface TournamentCardProps{
    children?: React.ReactNode
    className?: string
}

//Any copied and pasted code below was all hand-written and pasted for the sake of saving time, ai did not generate this code

export const MathTournamentCard = ({children, className} : TournamentCardProps) => {
    return(
        <MatchCard className={`flex flex-row w-[95%] relative ${className} overflow-x-auto`}>

                <div className="flex flex-col">
                    <div className="inset-0 right-2 text-muted-text ml-3 -mt-4.5 text-xs">#tid</div>
                    <Calculator size={50} className="ml-5 my-auto"/>
                </div>

                <div className="flex flex-col max-w-full h-full">
                    <div className="font-font font-semibold text-[1.5rem]">
                        Math Tournament
                    </div>
                    
                    <div className="flex flex-row gap-2">
                        <Timer size={20} className="text-muted-text my-auto"/>
                        <div className="font-font text-xs my-auto text-primary mt-0.5">Time Until Start:</div>
                    </div>
                    
                </div>

                {/* useless div for separation: */}
                <div>
                </div>

                <div className="flex flex-col ml-auto mr-5">
                    <div className="flex flex-row mt-1.5 w-[140%]">
                    <div className="font-font text-xs text-primary">Capacity: </div>
                    <div className="font-font text-xs text-primary ml-auto">5/8 Players</div>
                    </div>
                    <Progress value={62.5} className="mt-2 w-[130%] h-[0.5rem]"/>
                </div>

                <TournamentButton className="w-[9rem] h-[2.25rem] my-auto rounded-[11px] ml-auto mr-10">
                    <div className="flex flex-row w-full h-full gap-5">
                        <h2 className="font-font text-xs font-semibold w-[120%] my-auto">Join Tournament</h2>
                        <ArrowRight size={25} className="flex justify-self-end my-auto -ml-9 mr-1"/>
                    </div>
                </TournamentButton>

            {children}
        </MatchCard>
    )
}



//the code below was just copied from the MathTournamentCard code above and changed, all this code was human-written and was not generated by AI

export const ProgrammingTournamentCard = ({children, className} : TournamentCardProps) => {
    return(
        <MatchCard className={`flex flex-row w-[95%] relative ${className} overflow-x-auto`}>

                <div className="flex flex-col">
                    <div className="inset-0 right-2 text-muted-text ml-3 -mt-4.5 text-xs">#tid</div>
                    <CodeXml size={50} className="ml-5 my-auto"/>
                </div>

                <div className="flex flex-col max-w-full h-full">
                    <div className="font-font font-semibold text-[1.5rem]">
                        Programming Tournament
                    </div>
                    
                    <div className="flex flex-row gap-2">
                        <Timer size={20} className="text-muted-text my-auto"/>
                        <div className="font-font text-xs  my-auto text-primary mt-0.5">Time Until Start:</div>
                    </div>
                    
                </div>

                {/* useless div for separation: */}
                <div>
                </div>

                <div className="flex flex-col ml-auto mr-15">
                    <div className="flex flex-row mt-1.5 w-[140%]">
                        <div className="font-font text-xs text-primary">Capacity: </div>
                        <div className="font-font text-xs text-primary ml-auto">5/8 Players</div>
                    </div>
                    <Progress value={62.5} className="mt-2 w-[130%] h-[0.5rem]"/>
                </div>

                <TournamentButton className="w-[9rem] h-[2.25rem] my-auto rounded-[11px] ml-auto mr-10">
                    <div className="flex flex-row w-full h-full gap-5">
                        <h2 className="font-font text-xs font-semibold w-[120%] my-auto">Join Tournament</h2>
                        <ArrowRight size={30} className="flex justify-self-end my-auto -ml-9 mr-1"/>
                    </div>
                </TournamentButton>

            {children}
        </MatchCard>
    )
}