import { ChevronRight, ChevronLeft, ChevronUp, ChevronDown } from 'lucide-react'
import { useEffect } from 'react';
import { useMatch } from 'src/ViewModels/Match/MatchViewModel';

import MathMatch from '@/components/features/Match/MathPage';
import { Question } from '@/components/features/Questions/question';
import Loading from '@/components/shared/Loading';
import { MatchScreen } from '@/components/features/Match/Match';
import { Button } from '@/components/ui/button';
import Popup from '@/components/shared/PopUp';
import "../../../src/styles/global.css"
import { PowerUpAndDownButtons } from '@/components/features/Match/PowerUpandDownButtons';

const MathsMatch = () => {
    const {
        status,
        questions, answers, setAnswers,
        results,
        playerLife, avatars, usernames,
        seconds, minutes,
        currentQuestion,
        nextQuestion, prevQuestion,
        roundIdx, rounds,
        opponentCurrent, waitingOpponent, finishGame,
        loading, 
        submitQuestion, gameOver,
        mathfieldRef, 
        elos
    } = useMatch();

    const curr = questions[currentQuestion];

    //the following code was copied and pasted from an old version of this file 
    // and was hand-written and NOT generated by ai

    const correct = results[currentQuestion];
    const result_colour = () => {
        if (correct[currentQuestion] === true) return 'bg-success/50'
        else if (correct[currentQuestion] === false) return 'bg-danger/50'
        else return 'bg-white'
    }


    const read_only = () => {
        if (gameOver) return 'read-only'
        else return ''
    }
    

    useEffect(() => {
        if (mathfieldRef.current) {
            mathfieldRef.current.value = '';
        }
    }, [currentQuestion])


    if (loading || !curr) {
        return (
            <Loading isOpen={loading}></Loading>
        )
    }

    return (
        <MatchScreen
            player_life={playerLife}
            seconds={seconds}
            minutes={minutes}
            avatars={avatars}
            usernames={usernames}
            elos={elos}
            current_question={currentQuestion}
            opponent_progress={opponentCurrent}
            question_number={questions.length}
            question_results={results ?? []}
            rounds={rounds}
            current_round={roundIdx}
        >

            <Question
                className={` h-[20rem] mb-5`}
                difficulty={curr.difficulty!}
                title={curr.title!}
                description={curr.description}
                // number={currentQuestion + 1}
            />

            {/* add extra question component here */}

            
            <div className='w-[100%] h-full min-h-[35%] flex flex-col items-center justify-center'>
                <MathMatch
                    mathfieldRef={mathfieldRef}
                    onValueChange={(val) => setAnswers(prev => ({...prev, [currentQuestion]: val}))}
                    className={`${result_colour()}, ${read_only}`}
                >
                

            {/* the code below was copied from a more updated version of this file that wasn't merged properly,
            all this code was written by a human and was not generated with ai */}
            
            <div className='w-[100%] h-[6rem] flex flex-shrink-0 items-center justify-center gap-10 rounded-4xl mb-10 my-auto relative'>

                <div className='flex items-center justify-center text-secondary bg-primary rounded-2xl w-[15%]'>
                    <ChevronLeft onClick={() => prevQuestion(currentQuestion)} className='size-[3rem] hover:scale-110  hover:bg-secondary/20 rounded-2xl w-[50%]' />
                    <ChevronRight onClick={() => nextQuestion(currentQuestion)} className='size-[3rem] hover:scale-110 hover:bg-secondary/20 rounded-2xl w-[50%]' />
                </div>
                <Button className='w-[20%] h-[2.6rem] rounded-2xl text-[2rem] hover:-translate-y-1'
                    onClick={() => {
                        const answer = mathfieldRef.current?.value ?? '';
                        submitQuestion({ answer: answer })
                    }}
                >
                    Submit Answer
                </Button>
                {currentQuestion === (questions.length - 1) &&
                    <Button className='w-[20%] h-[2.6rem] rounded-2xl text-[2rem] hover:-translate-y-1'
                        onClick={() => {
                            finishGame();
                        }}
                    >
                        <p>Finish</p>
                    </Button>
                }
                <PowerUpAndDownButtons/>
            </div>
            </MathMatch>
            </div>

            {waitingOpponent && (
                <Popup
                    isOpen={waitingOpponent}
                    title={'Waiting For Opponent To Finish'}
                    subtitle={'Hang on while your opponent finishes up'}
                />
            )

            }
        </MatchScreen >
    )

}

export default MathsMatch;