import { CodeEditor } from "@/components/features/code-editor";
import { Question } from "@/components/features/Questions/question";
import { MatchScreen } from "@/components/features/Match/Match";
import { useMatch } from "src/ViewModels/Match/MatchViewModel"
import { ChevronRight, ChevronLeft } from 'lucide-react'
import Loading from '@/components/shared/Loading';
import { useState, useMemo, useEffect } from "react";
import TournamentButton from "@/components/features/Tournaments/TournamentButton";
import { MatchCard } from "@/components/features/Match/MatchCard";
import PopUp from "@/components/shared/PopUp";
import { useUser } from 'src/context/User/hooks/useUser';
import { Button } from "@/components/ui/button";
import Flash from "@/components/ui/animations/Flash";

export const ProgMatch = () => {
    const [code, setCode] = useState('');
    const [languageId, setLanguageId] = useState<number | null>(null);

    const {
        lastResult,
        myIndex,
        status,
        questions,
        results,
        playerLife, playerOneAvatar, playerTwoAvatar, usernames,
        seconds, minutes,
        currentQuestion, nextQuestion, prevQuestion,
        roundIdx, rounds,
        opponentCurrent, waitingOpponent, finishMatch,
        loading,
        submitQuestion, marking, markingError,
        elos, colourClass,
        final_question, complete_round, confirmCompleteRound, confirmRound, cancelCompleteRound, completeRound,
        matchType, matchMode
    } = useMatch();

    const curr = questions[currentQuestion];
    const question = useMemo(() => ({ templates: curr.templates }), [curr]);
    const { username } = useUser();
    const currentResult = results?.[roundIdx]?.[currentQuestion];

    const correct : boolean | null = results?.[roundIdx]?.[currentQuestion] ?? null;


     //the following block of code was copied from an older version of this file and was hand-written,
        //it was not generated by ai!
    
        const result_colour = () => {
            if (correct === true) return 'bg-success/50'
            else if (correct === false) return 'bg-danger/50'
            else return 'bg-card-tournament'
        }
    
        const result_border = () => {
            if(correct === true) return "border border-success"
            else if (correct === false) return "border border-danger"
            else return ""
        }
    
        const [flashTrigger, setFlashTrigger] = useState(0);
    
        useEffect(() => {
            if(correct !== null) {
                setFlashTrigger(t => t + 1);
            }
        }, [lastResult, currentQuestion, roundIdx, correct]);
    
        const myLife = myIndex >= 0 ? playerLife[myIndex] : undefined;
        const lowLife = myLife !== undefined && myLife >= 0 && myLife <= 25;
    
        /////////////////////////////////////////////////////////////////


    if (status !== 'ready' || !curr) {
        return (
            <Loading isOpen={loading}></Loading>
        )
    }

    return (
        <MatchScreen
            player_life={playerLife}
            seconds={seconds}
            minutes={minutes}
            playerOneAvatar={playerOneAvatar}
            playerTwoAvatar={playerTwoAvatar}
            usernames={usernames}
            elos={elos}
            current_question={currentQuestion}
            opponent_progress={opponentCurrent}
            question_number={questions.length}
            question_results={results ?? []}
            rounds={rounds}
            current_round={roundIdx}
            current_user={username}
    
        >
            {/* the following line of code was copied and pasted from another version of this file and was not generated by ai!!! */}
            {lowLife && <div className="danger-pulse pointer-events-none fixed inset-0 z-40"/>}

            <Question
                className={` h-[20rem] `}
                difficulty={curr.difficulty!}
                title={curr.title!}
                description={curr.description}
            />

            <MatchCard className={`items-center justify-center mt-5 ${colourClass}`}>
                <Flash
                    result={correct ?? null}
                    trigger={flashTrigger}
                    className="w-[100%] flex flex-col items-center justify-center mt-5 rounded-2xl">
                    <MatchCard className={`w-[95%] h-[95%] ${result_colour()} ${result_border()}`}>
                        <CodeEditor
                            question={question}
                            onChange={(new_code,  judge0_id) => {
                                setCode(new_code);
                                setLanguageId(judge0_id)
                            }}
                            className="ml-20 "

                        />
                    </MatchCard>
                </Flash>

                <div className='flex flex-row gap-5 flex-shrink-0 w-full mx-auto justify-center my-auto'>

                    <TournamentButton className='flex items-center justify-evenly text-secondary rounded-2xl w-[10%] h-auto'>
                        <ChevronLeft onClick={() => prevQuestion(currentQuestion)} className='size-[3rem] hover:scale-110  hover:bg-secondary/20 rounded-2xl w-[50%]' />
                        <ChevronRight onClick={() => nextQuestion(currentQuestion)} className='size-[3rem] hover:scale-110 hover:bg-secondary/20 rounded-2xl w-[50%]' />
                    </TournamentButton>
                    <Button className='w-[20%] h-[3.6rem] rounded-2xl text-[1rem] hover:-translate-y-1'
                        // disabled={marking}
                        onClick={async () => {
                            if (!marking && code.trim() && languageId !== null) {
                                await submitQuestion({
                                    source_code: code,
                                    language_id: languageId,
                                    stdin: null
                                }, matchType!,matchMode!)
                            }
                        }}
                    >
                        {marking ? 'Marking...' : 'Submit Answer'}
                    </Button>
                    {final_question ? (

                        <Button className='w-[20%] h-[3.6rem] rounded-2xl text-[1rem] hover:-translate-y-1'
                            onClick={async () => { await finishMatch(); }}
                        >
                            <p>Finish Match</p>
                        </Button>) :
                        complete_round && (
                            <Button className='w-[20%] h-[3.6rem] rounded-2xl text-[1rem] hover:-translate-y-1 my-auto'
                                onClick={() => { confirmCompleteRound() }}
                            >
                                <p>Complete Round</p>
                            </Button>
                        )
                    }

                    {
                        confirmRound && (
                            <div>
                                <p>You won't be able to go back once you've completed a round.</p>
                                <Button onClick={cancelCompleteRound}>Cancel</Button>
                                <Button onClick={completeRound}>Continue</Button>
                            </div>
                        )
                    }

                </div>

                {/* Judge0 runs every test case, so give explicit feedback rather than relying on the card flash alone */}
                <p className='text-center text-[0.95rem] font-semibold mb-3 min-h-[1.5rem]' aria-live='polite'>
                    {marking ? <span className='text-muted-text'>Running your code against the test cases...</span>
                        : markingError ? <span className='text-danger'>Could not mark submission: {markingError}</span>
                        : currentResult === true ? <span className='text-success'>Correct! All test cases passed.</span>
                        : currentResult === false ? <span className='text-danger'>Incorrect - some test cases failed.</span>
                        : null}
                </p>
            </MatchCard>
            {waitingOpponent && (
                <PopUp
                    isOpen={waitingOpponent}
                    title={'Waiting For Opponent To Finish'}
                    subtitle={'Hang on while your opponent finishes up'}
                />
            )}

        </MatchScreen >
    )
}